static/style.css
-problem with z-index fixed
-style of tooltip fixed
=> tooltip fixes

core.py, requirements.txt, start.py
- typecast integer from config file.
- comment out empty file errors (should remove in future).
- included requirements.txt.
- remove manual path entry.
https://github.com/kit-ipe/bora/issues/21
Signed-off-by: chanhoonseng <chanhoonseng3101@gmail.com>
=> implemented startup script.

core.py, static/HIU.svg
Signed-off-by: chanhoonseng <chanhoonseng3101@gmail.com>
=> Enable data entry with ending _Val for WGTS_01

designer_master.html, function/button/lambda.yaml, function/button/scripts/function_helper.py, function/button/scripts/main.py, js_plugins/button.js, services/rest/pyrest.py, template/README.md, template/button.html, typedef/button.yaml
https://github.com/kit-ipe/bora/issues/66
=> Added Button with rest call

README.md, core.py, js_plugins/button.js, services/rest/pyrest.py, status_master.html, template/button.html
https://github.com/kit-ipe/bora/issues/76
https://github.com/kit-ipe/bora/issues/69
=> Added config widget that takes configuration files via rest

function/hls/scripts/main.py, res/rtsp_docker/Dockerfile, res/rtsp_docker/README.md, res/rtsp_docker/run.sh, res/rtsp_docker/src/CMakeLists.txt, res/rtsp_docker/src/README.md, res/rtsp_docker/src/rtsp.c, static_master/style.css, status_master.html, template/hls.html
https://github.com/kit-ipe/bora/issues/65
=> Added crosshair 

blueprint/designer.html, core.py, typedef/adei.yaml, typedef/box.yaml, typedef/button.yaml, typedef/graph.yaml, typedef/hls.yaml, typedef/icon.yaml, typedef/iframe.yaml, typedef/input.yaml, typedef/integer_to_string.yaml, typedef/readonly.yaml, typedef/rest.yaml, typedef/text.yaml
- removed datatype
- settings.yaml no longer required plugins
- plugin list will be read automatically from typedef folder
- all yaml files removed data key
- this solution default yes to all plugins
- designer.html can dynamically select plugins via checkbox
=> Implemented dynamic plugin selection

core.py, start.py
a) create settings.yaml, style yaml and varname.yaml with contents b) git clone bora repo from kit-ipe
c) install bora requirement txt
d) copy background.png from bora to current working directory as default image e) questionnaire asking user for project
2. Debug cache
=> 1. Created a python script which run the following process:

blueprint/designer.html, requirements.txt
2. Adding Redis package in requirements.txt
=> 1. Bug fixes in designer.html

core.py
Signed-off-by: nadou101 <nadiaaouadi01@gmail.com>
=> Removed unused code in core.py

blueprint/designer.html, core.py, typedef/box.yaml
1. deleted some comments in core.py
2. add text field in box.yaml
3. code enhancement and bug fixes in add, remove, select, update and save function at designer.html
4. removed span element and reposition font-size and font-weight to div for text plugin html template
=> Verified text plugin and box plugin

blueprint/designer.html, core.py
=> Adding sensor names to plugins

blueprint/designer.html, core.py, typedef/adei.yaml, typedef/box.yaml, typedef/button.yaml, typedef/input.yaml, typedef/integer_to_string.yaml, typedef/readonly.yaml, typedef/rest.yaml, typedef/text.yaml
=> successfully resolved the conflict

blueprint/designer.html, blueprint/status.html, core.py, parser.py, requirements.txt
Two sides of polling were added: the server reads data from external sources and pushes it to the Redis database. Then, the browser uses Ajax to continuously poll data from core.py.
=> added the data flow that reads from redis and push to status.html

blueprint/designer.html
https://github.com/kit-ipe/bora/issues/136#event-12924677519
=> Verify adei

blueprint/status.html, template/adei.html
status page now shows adei values.
Yet, we still need additional attributes that Yihan will provide to perform further data decorating.
=> Added adei html to display incoming data

blueprint/designer.html, blueprint/status.html, core.py, function/calc/scripts/function_helper.py, function/icon/scripts/function_helper.py, function/icon/scripts/main.py, function/integer_to_string/scripts/function_helper.py, function/integer_to_string/scripts/main.py, js_plugins/icon.js, js_plugins/integer_to_string.js, requirements.txt, template/icon.html, template/integer_to_string.html, typedef/icon.yaml
Updated status functions for integer-to-string and icon
=> Updated status functions for integer-to-string and icon

blueprint/designer.html, js_plugins/calc.js
Apparently, I couldn't reproduce this bug. Hence it will be marked solved.
https://github.com/kit-ipe/bora/issues/146
=> removed debug messages

blueprint/designer.html, typedef/calc.yaml
1. add <span class='text_name'> for both text and box
2. text_name for calc plugin changes to optional since its id is now generate by uid
=> Text_name field not showing when selecting them in text and box plugin

blueprint/designer.html, function/clone/lambda.yaml, function/clone/scripts/function_helper.py, function/clone/scripts/main.py, function/virtual/lambda.yaml, function/virtual/scripts/function_helper.py, function/virtual/scripts/main.py, js_plugins/clone.js, js_plugins/virtual.js, template/clone.html, template/virtual.html, typedef/clone.yaml, typedef/virtual.yaml
1. creates a yaml file, a js file, a html file and function folder for both plugins
2. added html template for both plugins in designer.html
3. modified some parts in bora_add, bora_select and bora_update to accommodate these new plugins
=> Created Virtual and Clone Plugins

blueprint/designer.html
1. replace(/"/g, "'") when adding int_to_str
2. replace(/'/g, '"') when saving int_to_str
=> Solved quotation issue in integer_to_string plugin

blueprint/status.html, js_plugins/calc.js, js_plugins/virtual.js, template/adei.html, template/virtual.html, typedef/virtual.yaml
updated virtual in status display
=> updated virtual in status display

blueprint/designer.html, template/icon.html
1. it does not save the icon's width and height initially
2. changed the icon's html template in these 2 files: designer.html & icon.html
=> Solved icon bug

blueprint/designer.html, template/icon.html, typedef/icon.yaml
1. icon-type is now a data (nodata previously)
=> Modified part of the codes in bora_save to retrieve icon type

js_plugins/adei.js, js_plugins/calc.js
Fixing conditionals error in adei.js and calc.js so that it will shows the correct color based on value entered by user in data_smaller and data_larger fields.
=> Fixing conditionals error in adei and calc

core.py, js_plugins/adei.js, js_plugins/calc.js
1. fixing the exponential error in adei.js
2. changes the conditions in calc plugins (black to green)
3. deleted encoding utf8 in core.py of class SaveHandler
=> Exponential Error and Conditional Fixing
